### ISSUE TITLE
Errors when I run this plugin.

### ISSUE THREAD

**Issue by jimi1104** [KPGTB/KTools#3]
[16:10:46 ERROR]: [KTools] Failed to register events for class com.github.kpgtb.ktools.listener.GSitListener because dev/geco/gsit/api/event/PlayerGetUpPlayerSitEvent does not exist.
[16:10:48 WARN]: [KTools] Task #2 for KTools v2.4.5-SNAPSHOT generated an exception
java.lang.RuntimeException: UiManager is not supported! UI requirements: ProtocolLib & Minecraft Version 1.14+
        at com.github.kpgtb.ktools.manager.ui.bar.BarManager.prepareBars(BarManager.java:106) ~[KTools-min-2.4.5-SNAPSHOT.jar:?]
        at com.github.kpgtb.ktools.KTools$1.run(KTools.java:169) ~[KTools-min-2.4.5-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:91) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:479) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:26:17 ERROR]: Could not pass event PlayerJoinEvent to KTools v2.4.5-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "com.github.kpgtb.ktools.manager.ui.UiManager.addUI(java.util.UUID, com.github.kpgtb.ktools.manager.ui.BaseUiObject)" because the return value of "com.github.kpgtb.ktools.util.wrapper.ToolsObjectWrapper.getUiManager()" is null
        at com.github.kpgtb.ktools.manager.ui.bar.BarManager.showBar(BarManager.java:153) ~[KTools-min-2.4.5-SNAPSHOT.jar:?]
        at com.github.kpgtb.ktools.listener.JoinListener.lambda$onJoin$0(JoinListener.java:77) ~[KTools-min-2.4.5-SNAPSHOT.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1073) ~[?:?]
        at com.github.kpgtb.ktools.listener.JoinListener.onJoin(JoinListener.java:75) ~[KTools-min-2.4.5-SNAPSHOT.jar:?]        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor3.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:65) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:352) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:207) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:188) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:87) ~[?:?]        at net.minecraft.network.Connection.tick(Connection.java:611) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1402) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by KPGTB** [comment]
UI requirements: ProtocolLib
